
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 17;
  public static final int LETRA_MINUS = 11;
  public static final int MENOS = 25;
  public static final int LLAVE_ABRE = 2;
  public static final int CONCATENACION = 18;
  public static final int LLAVE_CIERRA = 4;
  public static final int CERRADURA_POSITIVA = 21;
  public static final int CONJUNTO = 15;
  public static final int DOS_PUNTOS = 6;
  public static final int SEPARADOR = 3;
  public static final int COMA = 14;
  public static final int ASIGNACION = 8;
  public static final int COMILLA_DOBLE = 16;
  public static final int EOF = 0;
  public static final int DIGITO = 12;
  public static final int CONJ = 5;
  public static final int error = 1;
  public static final int ENTRADA = 24;
  public static final int CERRADURA_KLENEE = 20;
  public static final int ALTERNANCIA = 19;
  public static final int OPCIONAL = 22;
  public static final int IDENTIFICADOR = 7;
  public static final int PUNTO_COMA = 9;
  public static final int SALTO = 23;
  public static final int LETRA_MAYUS = 10;
  public static final int CONJ_ASCII = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_ABRE",
  "SEPARADOR",
  "LLAVE_CIERRA",
  "CONJ",
  "DOS_PUNTOS",
  "IDENTIFICADOR",
  "ASIGNACION",
  "PUNTO_COMA",
  "LETRA_MAYUS",
  "LETRA_MINUS",
  "DIGITO",
  "CONJ_ASCII",
  "COMA",
  "CONJUNTO",
  "COMILLA_DOBLE",
  "COMILLA_SIMPLE",
  "CONCATENACION",
  "ALTERNANCIA",
  "CERRADURA_KLENEE",
  "CERRADURA_POSITIVA",
  "OPCIONAL",
  "SALTO",
  "ENTRADA",
  "MENOS"
  };
}

